# Generated by Django 2.1.7 on 2019-02-22 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_auto_20190222_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='posted_by',
            field=models.ForeignKey(help_text='Usuário que postou o link', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='Identificador do link'),
        ),
    ]
